name: Load Test Weather API

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'API Base URL'
        required: true
        default: 'https://localhost:7001'
      concurrent_users:
        description: 'Concurrent Users'
        required: true
        type: choice
        options:
          - '10'
          - '50'
          - '100'
          - '500'
      duration_seconds:
        description: 'Test Duration (seconds)'
        required: true
        default: '60'

jobs:
  load-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install k6 (load testing tool)
      run: |
        sudo gpg -k
        sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6
    
    - name: Create load test script
      run: |
        cat > loadtest.js << 'EOF'
        import http from 'k6/http';
        import { check, sleep } from 'k6';

        export const options = {
          vus: ${{ inputs.concurrent_users }},
          duration: '${{ inputs.duration_seconds }}s',
        };

        export default function () {
          const res = http.get('${{ inputs.target_url }}/api/cities');
          check(res, {
            'status is 200': (r) => r.status === 200,
            'response time < 500ms': (r) => r.timings.duration < 500,
          });
          sleep(1);
        }
        EOF
    
    - name: Run load test
      run: k6 run loadtest.js
    
    - name: Test summary
      run: |
        echo "### Load Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Target:** ${{ inputs.target_url }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Users:** ${{ inputs.concurrent_users }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Duration:** ${{ inputs.duration_seconds }}s" >> $GITHUB_STEP_SUMMARY
